name: LeetCode Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch LeetCode Data
        run: |
          curl -X POST https://leetcode.com/graphql \
            -H "Content-Type: application/json" \
            -d '{"query":"query getUserProfile($username: String!) { matchedUser(username: $username) { submitStats { acSubmissionNum { difficulty count } } profile { ranking } }","variables":{"username":"ananymishradev"}}' \
            > leetcode.json || echo '{"solved":0,"ranking":"N/A"}' > leetcode.json

      - name: Generate SVG
        run: |
          python scripts/generate_svg.py  # Your existing script
          git config user.name "GitHub Actions"
          git add leetcode.json stats.svg
          git commit -m "Update stats"
          git push
